# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "rtfm"
client_id = "1c5487352699fc307724640edf7dbf77"
application_url = "https://llp-arrest-filme-decline.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://llp-arrest-filme-decline.trycloudflare.com/auth/callback",
  "https://llp-arrest-filme-decline.trycloudflare.com/auth/shopify/callback",
  "https://llp-arrest-filme-decline.trycloudflare.com/api/auth/callback",
  "https://llp-arrest-filme-decline.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sonda-apparel.myshopify.com"
